void keyPressed(){
  if(key=='s'||key=='S'){
    skey=true;
  }
  if(key=='w'||key=='W'){
    wkey=true;
  }
  if(key=='a'||key=='A'){
    akey=true;
  }
  if(key=='d'||key=='D'){
    dkey=true;
  }
  if(keyCode==DOWN){
    downkey=true;
  }
  if(keyCode==UP){
    upkey=true;
  }
  if(keyCode==RIGHT){
    downkey=true;
  }
  if(keyCode==LEFT){
    downkey=true;
  }
  if(key==' '){
    spacekey=true;
  }
}
void keyReleased(){
  if(key=='s'||key=='S'){
    skey=false;
  }
  if(key=='w'||key=='W'){
    wkey=false;
  }
  if(key=='a'||key=='A'){
    akey=false;
  }
  if(key=='d'||key=='D'){
    dkey=false;
  }
  if(keyCode==DOWN){
    downkey=false;
  }
  if(keyCode==UP){
    upkey=false;
  }
  if(keyCode==RIGHT){
    downkey=false;
  }
  if(keyCode==LEFT){
    downkey=false;
  }
  if(key==' '){
    spacekey=false;
  }
}
