void keyPressed(){
  if(key=='s'||key=='S'){
    keys[skey]=true;
  }
  if(key=='w'||key=='W'){
    keys[wkey]=true;
  }
  if(key=='a'||key=='A'){
    keys[akey]=true;
  }
  if(key=='d'||key=='D'){
    keys[dkey]=true;
  }
  if(keyCode==DOWN){
    keys[downkey]=true;
  }
  if(keyCode==UP){
    keys[upkey]=true;
  }
  if(keyCode==RIGHT){
    keys[rightkey]=true;
  }
  if(keyCode==LEFT){
    keys[leftkey]=true;
  }
  if(key==' '){
    keys[spacekey]=true;
  }
}
void keyReleased(){
  if(key=='s'||key=='S'){
    keys[skey]=false;
  }
  if(key=='w'||key=='W'){
    keys[wkey]=false;
  }
  if(key=='a'||key=='A'){
    keys[akey]=false;
  }
  if(key=='d'||key=='D'){
    keys[dkey]=false;
  }
  if(keyCode==DOWN){
    keys[downkey]=false;
  }
  if(keyCode==UP){
    keys[upkey]=false;
  }
  if(keyCode==RIGHT){
    keys[rightkey]=false;
  }
  if(keyCode==LEFT){
    keys[leftkey]=false;
  }
  if(key==' '){
    keys[spacekey]=false; 
  }
}
